### ISSUE TITLE
Installation of the Python package

### ISSUE THREAD

**Issue by TheQubitGuy** [Classiq-Technologies/Internal#2]
Tried installing the ClassiqSDK according to the instructions in the manual.

pip install fails. See the log below

pip install --upgrade pip                                         
Requirement already satisfied: pip in ./venv/lib/python3.8/site-packages (21.2.4)
(venv) yuvalboger@Yuvals-MBP Cadmium % pip install 'classiq[all]'
Requirement already satisfied: classiq[all] in ./venv/lib/python3.8/site-packages (0.1.0)
WARNING: classiq 0.1.0 does not provide the extra 'all'
Requirement already satisfied: ConfigArgParse<2.0,>=1.5 in ./venv/lib/python3.8/site-packages (from classiq[all]) (1.5.1)
Requirement already satisfied: networkx<3.0.0,>=2.5.1 in ./venv/lib/python3.8/site-packages (from classiq[all]) (2.6.2)
Requirement already satisfied: numpy<2.0.0,>=1.20.1 in ./venv/lib/python3.8/site-packages (from classiq[all]) (1.21.1)
Requirement already satisfied: pydantic<2.0.0,>=1.8.2 in ./venv/lib/python3.8/site-packages (from classiq[all]) (1.8.2)
Requirement already satisfied: websockets<10.0,>=9.1 in ./venv/lib/python3.8/site-packages (from classiq[all]) (9.1)
Requirement already satisfied: httpx<0.19.0,>=0.18.2 in ./venv/lib/python3.8/site-packages (from classiq[all]) (0.18.2)
Requirement already satisfied: more-itertools<9.0.0,>=8.7.0 in ./venv/lib/python3.8/site-packages (from classiq[all]) (8.8.0)
Collecting qiskit<0.29.0,>=0.28.0
  Downloading qiskit-0.28.0.tar.gz (12 kB)
Requirement already satisfied: Pyomo<7.0.0,>=6.0.1 in ./venv/lib/python3.8/site-packages (from classiq[all]) (6.1.1)
Requirement already satisfied: keyring<24.0.0,>=23.0.1 in ./venv/lib/python3.8/site-packages (from classiq[all]) (23.0.1)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in ./venv/lib/python3.8/site-packages (from httpx<0.19.0,>=0.18.2->classiq[all]) (1.5.0)
Requirement already satisfied: httpcore<0.14.0,>=0.13.3 in ./venv/lib/python3.8/site-packages (from httpx<0.19.0,>=0.18.2->classiq[all]) (0.13.6)
Requirement already satisfied: sniffio in ./venv/lib/python3.8/site-packages (from httpx<0.19.0,>=0.18.2->classiq[all]) (1.2.0)
Requirement already satisfied: certifi in ./venv/lib/python3.8/site-packages (from httpx<0.19.0,>=0.18.2->classiq[all]) (2021.5.30)
Requirement already satisfied: anyio==3.* in ./venv/lib/python3.8/site-packages (from httpcore<0.14.0,>=0.13.3->httpx<0.19.0,>=0.18.2->classiq[all]) (3.3.0)
Requirement already satisfied: h11<0.13,>=0.11 in ./venv/lib/python3.8/site-packages (from httpcore<0.14.0,>=0.13.3->httpx<0.19.0,>=0.18.2->classiq[all]) (0.12.0)
Requirement already satisfied: idna>=2.8 in ./venv/lib/python3.8/site-packages (from anyio==3.*->httpcore<0.14.0,>=0.13.3->httpx<0.19.0,>=0.18.2->classiq[all]) (3.2)
Requirement already satisfied: importlib-metadata>=3.6 in ./venv/lib/python3.8/site-packages (from keyring<24.0.0,>=23.0.1->classiq[all]) (4.6.4)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.8/site-packages (from importlib-metadata>=3.6->keyring<24.0.0,>=23.0.1->classiq[all]) (3.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./venv/lib/python3.8/site-packages (from pydantic<2.0.0,>=1.8.2->classiq[all]) (3.10.0.0)
Requirement already satisfied: ply in ./venv/lib/python3.8/site-packages (from Pyomo<7.0.0,>=6.0.1->classiq[all]) (3.11)
Collecting qiskit-terra==0.18.0
  Downloading qiskit_terra-0.18.0-cp38-cp38-macosx_10_9_x86_64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 3.0 MB/s 
Requirement already satisfied: qiskit-aer==0.8.2 in ./venv/lib/python3.8/site-packages (from qiskit<0.29.0,>=0.28.0->classiq[all]) (0.8.2)
Collecting qiskit-ibmq-provider==0.15.0
  Downloading qiskit_ibmq_provider-0.15.0-py3-none-any.whl (234 kB)
     |████████████████████████████████| 234 kB 18.5 MB/s 
Requirement already satisfied: qiskit-ignis==0.6.0 in ./venv/lib/python3.8/site-packages (from qiskit<0.29.0,>=0.28.0->classiq[all]) (0.6.0)
Requirement already satisfied: qiskit-aqua==0.9.4 in ./venv/lib/python3.8/site-packages (from qiskit<0.29.0,>=0.28.0->classiq[all]) (0.9.4)
Requirement already satisfied: scipy>=1.0 in ./venv/lib/python3.8/site-packages (from qiskit-aer==0.8.2->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.6.1)
Requirement already satisfied: pybind11>=2.6 in ./venv/lib/python3.8/site-packages (from qiskit-aer==0.8.2->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.7.1)
Requirement already satisfied: fastdtw<=0.3.4 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.3.4)
Requirement already satisfied: sympy>=1.3 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.8)
Requirement already satisfied: h5py<3.3.0 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (3.2.1)
Requirement already satisfied: pandas in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.3.2)
Requirement already satisfied: retworkx>=0.8.0 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.9.0)
Requirement already satisfied: dlx<=1.0.4 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.0.4)
Requirement already satisfied: yfinance<0.1.63 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.1.62)
Requirement already satisfied: psutil>=5 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (5.8.0)
Requirement already satisfied: scikit-learn>=0.20.0 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.24.2)
Requirement already satisfied: quandl in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (3.6.1)
Requirement already satisfied: docplex>=2.21.207 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.21.207)
Requirement already satisfied: setuptools>=40.1.0 in ./venv/lib/python3.8/site-packages (from qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (47.1.0)
Requirement already satisfied: requests>=2.19 in ./venv/lib/python3.8/site-packages (from qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.26.0)
Requirement already satisfied: urllib3>=1.21.1 in ./venv/lib/python3.8/site-packages (from qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.26.6)
Requirement already satisfied: requests-ntlm>=1.1.0 in ./venv/lib/python3.8/site-packages (from qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.0 in ./venv/lib/python3.8/site-packages (from qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.8.2)
Requirement already satisfied: websocket-client>=1.0.1 in ./venv/lib/python3.8/site-packages (from qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.2.1)
Requirement already satisfied: jsonschema>=2.6 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (3.2.0)
Requirement already satisfied: python-constraint>=1.4 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.4.0)
Requirement already satisfied: symengine>0.7 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.7.2)
Requirement already satisfied: fastjsonschema>=2.10 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.15.1)
Requirement already satisfied: dill>=0.3 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.3.4)
Requirement already satisfied: tweedledum<2.0,>=1.1 in ./venv/lib/python3.8/site-packages (from qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.1.0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from docplex>=2.21.207->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./venv/lib/python3.8/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in ./venv/lib/python3.8/site-packages (from jsonschema>=2.6->qiskit-terra==0.18.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (21.2.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venv/lib/python3.8/site-packages (from requests>=2.19->qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.0.4)
Requirement already satisfied: ntlm-auth>=1.0.2 in ./venv/lib/python3.8/site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.5.0)
Requirement already satisfied: cryptography>=1.3 in ./venv/lib/python3.8/site-packages (from requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (3.4.7)
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.8/site-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.14.6)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibmq-provider==0.15.0->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.20)
Requirement already satisfied: joblib>=0.11 in ./venv/lib/python3.8/site-packages (from scikit-learn>=0.20.0->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv/lib/python3.8/site-packages (from scikit-learn>=0.20.0->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (2.2.0)
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.8/site-packages (from sympy>=1.3->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (1.2.1)
Requirement already satisfied: multitasking>=0.0.7 in ./venv/lib/python3.8/site-packages (from yfinance<0.1.63->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.0.9)
Requirement already satisfied: lxml>=4.5.1 in ./venv/lib/python3.8/site-packages (from yfinance<0.1.63->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (4.6.3)
Requirement already satisfied: pytz>=2017.3 in ./venv/lib/python3.8/site-packages (from pandas->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (2021.1)
Requirement already satisfied: inflection>=0.3.1 in ./venv/lib/python3.8/site-packages (from quandl->qiskit-aqua==0.9.4->qiskit<0.29.0,>=0.28.0->classiq[all]) (0.5.1)
Using legacy 'setup.py install' for qiskit, since package 'wheel' is not installed.
Installing collected packages: qiskit-terra, qiskit-ibmq-provider, qiskit
  Attempting uninstall: qiskit-terra
    Found existing installation: qiskit-terra 0.18.1
    Uninstalling qiskit-terra-0.18.1:
      Successfully uninstalled qiskit-terra-0.18.1
  Attempting uninstall: qiskit-ibmq-provider
    Found existing installation: qiskit-ibmq-provider 0.16.0
    Uninstalling qiskit-ibmq-provider-0.16.0:
      Successfully uninstalled qiskit-ibmq-provider-0.16.0
  Attempting uninstall: qiskit
    Found existing installation: qiskit 0.29.0
    Uninstalling qiskit-0.29.0:
      Successfully uninstalled qiskit-0.29.0
    Running setup.py install for qiskit ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
visualization 0.1.0 requires setuptools<58.0.0,>=57.4.0, but you have setuptools 47.1.0 which is incompatible.
qiskit-optimization 0.2.2 requires networkx<2.6,>=2.2, but you have networkx 2.6.2 which is incompatible.
combinatorial-optimization 0.1.0 requires qiskit<0.30.0,>=0.29.0, but you have qiskit 0.28.0 which is incompatible.

**Comment by yehuda-naveh** [comment]
Thanks @TheQubitGuy . Please add exactly one label starting with a number - I suggest looking at #1 before you add, the semantics are not trivial. I added 1 for now.

@ofekkir @ravidalon I agree this is critical. Once/if you find out it is local to @TheQubitGuy or otherwise does not affect IonQ, it can be settled to 3 or even 4, depending on the cause of this

**Comment by yehuda-naveh** [comment]
@TheQubitGuy please proceed with running as in the document. Let us know if it runs correctly and if not where and what error you get. If all runs good (strong probability), you can consider the PIP error as a warning only

**Comment by yehuda-naveh** [comment]
It works on my side, I get another issue when calling the backend which may or may not be what @TheQubitGuy and @nir-minerbi seen yesterday. I'll send error stack to @ofekkir in the context it was raised yesterday. I'm demoting this one to  4/question because it seems to be only on @TheQubitGuy local environment, and more than that most probably (until we hear otherwise) it may not impact ability to run the code - just a pip warning

**Comment by TheQubitGuy** [comment]
Installation took several hours (this is on a 2021 MBP with M1).

Was filled with warning. The terminal output is attached. You'll see that I stopped it the first time, updated pip, and then ran again.

I then tried to run the authentication code:

import asyncio
import classiq

asyncio.run(classiq.authenticate())


and it failed:

/Users/yuvalboger/PycharmProjects/SDKTest/venv/bin/python /Users/yuvalboger/PycharmProjects/SDKTest/main.py
Traceback (most recent call last):
  File "/Users/yuvalboger/PycharmProjects/SDKTest/main.py", line 2, in <module>
    import classiq
  File "/Users/yuvalboger/PycharmProjects/SDKTest/venv/lib/python3.8/site-packages/classiq/__init__.py", line 3, in <module>
    from classiq.client import configure
  File "/Users/yuvalboger/PycharmProjects/SDKTest/venv/lib/python3.8/site-packages/classiq/client.py", line 6, in <module>
    from classiq_interface.server import authentication
ModuleNotFoundError: No module named 'classiq_interface'

Process finished with exit code 1

**Comment by TheQubitGuy** [comment]
[installerr.txt](https://github.com/Classiq-Technologies/Internal/files/7103136/installerr.txt)

**Comment by yehuda-naveh** [comment]
Ok if it was with a good internet connection I'm surprised by the time. It seems you still don't have the entire package installed

@ofekkir you may give it a look but if you think it is not a general issue then for now I would not give it the full attention

**Comment by yehuda-naveh** [comment]
@TheQubitGuy one thing I would try is to start from a completely clean environment. I would guess that there are some leftovers from previous installations. Also try 
pip install classiq_interface though @ofekkir may correct me on the exact name

**Comment by yehuda-naveh** [comment]
And of course if all else fails you still have the textual model, presuming that it works

**Comment by TheQubitGuy** [comment]
The textual model works. But I wanted to test the python for QA reasons - to understand what customers would experience.

The computer is on high-speed Internet. About 150 Mbps when I measured this morning. The delays were not in the download but in the pip install analysis of each package.

I did start from a completely new project (Ofek helped me set up venv a couple of weeks ago). BTW, I also tried it on an existing project and was not successful.

You can decide if you think this is a very specific issue for my machine or something that might impact others. I'm happy to do a remote 'Slack huddle' session if it helps

**Comment by yehuda-naveh** [comment]
Thanks we'll check and decide

**Comment by ravidalon** [comment]
@TheQubitGuy Since you already have the package install, you need to update it rather than install from scratch. Run the following command:
pip install --upgrade 'classiq[all]'

**Comment by TheQubitGuy** [comment]
I tried upgrading.

It ran for several hours, but after the upgrade, the simple code still gives the same exception

**Comment by yehuda-naveh** [comment]
We haven't encountered it yet with other parties, but it may well be the case as we still can't reproduce or explain. We should understand this

**Comment by ofekkir** [comment]
This is weird. It does not effect IonQ (as they have managed to authenticate through the SDK already).
I suggest we set a time to debug that (I prefer next week if possible) @TheQubitGuy

**Comment by jond01** [comment]
@TheQubitGuy - this issue could not be reproduced in a sterile environment.
Please create a new and sterile environment and
`pip install "classic[all]"`

See also https://classiq.atlassian.net/browse/CAD-328
