### ISSUE TITLE
Login screen appearance

### ISSUE THREAD

**Issue by TheQubitGuy** [Classiq-Technologies/Internal#8]
The logo on the login screen is too small and can hardly be seen.

Please use the attached pink version instead

![image](https://user-images.githubusercontent.com/83417636/132059165-00ade9b8-e5ea-43c7-a13b-2d96a8f46225.png)

![classiq_RGB_Pink](https://user-images.githubusercontent.com/83417636/132059269-315281b7-cfa8-4369-81ba-32a289e4c015.png)

**Comment by ofekkir** [comment]
Are you sure using a png will solve that? Shouldn't we use an .svg?

**Comment by TheQubitGuy** [comment]
I don't mind either way. The SVG is attached if you prefer it.

**Comment by ofekkir** [comment]
I'll try it. Thanks!

**Comment by ofekkir** [comment]
Wait, where is it? @TheQubitGuy

**Comment by TheQubitGuy** [comment]
Sorry - Github does not support attaching SVG.

It is here: https://drive.google.com/file/d/15JlOooY5hfa2nr6ePSOGMWnAAkddl7Lg/view?usp=sharing

**Comment by ofekkir** [comment]
Fixed.
